# These are supported funding model platforms

github:
patreon:
ko_fi: aventratechnology
tidelift:
community_bridge:
liberapay: Aventra_Technology
open_collective:
issuehunt:
otechie:

custom: 
  - "https://aventra.technology/donate"
  - "https://boosty.to/aventra_technology/donate"
  - "https://send.monobank.ua/jar/3ZpomEpNky"
